;(function($){$.fn.pagination=function(pageCount,opts){opts=$.extend({prevPageText:"上一�?",nextPageText:"下一�?",middleDisplayPageCount:4,showPageInput:false,callback:function(){return false;}},opts||{});return this.each(function(){var currentPage=1,parentNode=this;function pageLinkHandler(pageIndex,evt){currentPage=pageIndex;render();var continuePropagation=opts.callback(pageIndex,parentNode);if(!continuePropagation&&evt){if(evt.stopPropagation){evt.stopPropagation();}else{evt.cancelBubble=true;}}
return continuePropagation;}
function getClickHandler(pageIndex){return function(evt){return pageLinkHandler(pageIndex,evt);};}
function getLinkItem(pageIndex,config){pageIndex=pageIndex<1?1:pageIndex;pageIndex=pageIndex<pageCount?pageIndex:pageCount;config=$.extend({text:pageIndex,classes:''},config||{});var $link=null;if(pageIndex===currentPage){$link=$('<span class="current">'+config.text+'</span>');}else{$link=$('<a href="javascript:;">'+config.text+'</a>').on('click',getClickHandler(pageIndex));}
if(config.classes){$link.addClass(config.classes);}
return $link;}
function render(){if(!pageCount){$(parentNode).empty();return;}
var frag=document.createDocumentFragment(),$frag=$(frag),halfPageCount=Math.ceil(opts.middleDisplayPageCount/2);var $prevPageLink=getLinkItem(currentPage-1,{text:opts.prevPageText});$frag.append($prevPageLink);var $firstPageLink=getLinkItem(1,{text:1});$frag.append($firstPageLink);if(currentPage-halfPageCount-2>0){$frag.append('<span>...</span>');}
var startPage=currentPage-halfPageCount>1?currentPage-halfPageCount:2,endPage=currentPage+halfPageCount<pageCount?currentPage+halfPageCount:pageCount-1;for(var i=startPage;i<=endPage;i++){var $pageLink=getLinkItem(i,{text:i});$frag.append($pageLink);}
if(currentPage+halfPageCount+1<pageCount){$frag.append('<span>...</span>');}
if(pageCount>1){var $lastPageLink=getLinkItem(pageCount,{text:pageCount});$frag.append($lastPageLink);}
var $nextPageLink=getLinkItem(currentPage+1,{text:opts.nextPageText});$frag.append($nextPageLink);if(opts.showPageInput){var $pageInput=$('<input class="pageInput" type="text" />');$frag.append($pageInput);var $pageBtn=$('<a href="'+opts.link_to+'">GO</a>');$pageBtn.on('click',function(evt){var pageIndex=$pageInput.val();if(/^[1-9]+.?[0-9]*$/.test(pageIndex)){pageIndex=parseInt(pageIndex,10);if(pageIndex>pageCount){pageIndex=pageCount;}
pageLinkHandler(pageIndex,evt);}
return false;});$frag.append($pageBtn);}
$container=$('<div class="pageinner cf" ></div>');$container.append($frag);$(parentNode).empty().append($container);}
render();});};})(jQuery);;(function($){var _util=CS.util,_bookshelf=CS.bookshelf;var _params={},_pager=null;var _showType=1;function init(searchInfo,getBookList_ajaxUrl){_params.searchInfo=searchInfo||{};_params.getBookList_ajaxUrl=getBookList_ajaxUrl||'';_bindEvent();_setNavActiveStyle();}
function _bindEvent(){_switchShowTab();_bindBookListEvent();$("#pageSizeSelect").change(function(){var url=$(this).val();if(url){window.location.href=url;}});$('#detailedlyShow').click(function(){$('#detailedBookListPanel').show();$('#simpleBookListPanel').hide();$(this).parent().removeClass('list_b');});$('#simplyShow').click(function(){$('#simpleBookListPanel').show();$('#detailedBookListPanel').hide();$(this).parent().addClass('list_b');});}
function _bindBookListEvent(){$('#detailedBookList  [actiontype="addtobookshelf"]').on('click',function(){var bid=$(this).attr('bid');_bookshelf.addToBookshelf(bid);return false;});}
function _setNavActiveStyle(){if(_params.searchInfo.Website===1||_params.searchInfo.Website==='1'){$("#a_Website_active_"+_params.searchInfo.Website).attr("class","active");$("#a_mm_Subjectid_active_"+_params.searchInfo.Subjectid).attr("class","active");}else{$("#a_Contentid_active_"+_params.searchInfo.Contentid).attr("class","active");$("#a_Subjectid_active_"+_params.searchInfo.Subjectid).attr("class","active");}
$("#a_TagList_active_"+_params.searchInfo.TagList).attr("class","active");$("#a_TagList1_active_"+_params.searchInfo.TagList).attr("class","active");if(_params.searchInfo.TagList!=='all'){$('.hidetag').show();$('.showtag').hide();}
$("#a_Bookwords_active_"+_params.searchInfo.Bookwords).attr("class","active");$("#a_Updatestatus_active_"+_params.searchInfo.Updatestatus).attr("class","active");$("#a_Lastupdate_active_"+_params.searchInfo.Lastupdate).attr("class","active");$("#a_Isvip_active_"+_params.searchInfo.Isvip).attr("class","active");if(_params.searchInfo.TitlePinyin===''){$("#a_TitlePinyin_active_"+_params.searchInfo.TitlePinyin).attr("class","alpha");}else{$("#a_TitlePinyin_active_"+_params.searchInfo.TitlePinyin).attr("class","alpha alphaAct");}
$("#a_Sortby_active_"+_params.searchInfo.Sortby).attr("class","active");}
function _getBookList(pageIndex,isLoadPage){isLoadPage=isLoadPage||false;var pageSize=$("#selectPageNumber").val();_util.request({url:_params.getBookList_ajaxUrl,data:{pageIndex:pageIndex,Website:_params.searchInfo.Website,Subjectid:_params.searchInfo.Subjectid,Contentid:_params.searchInfo.Contentid,Bookwords:_params.searchInfo.Bookwords,Lastupdate:_params.searchInfo.Lastupdate,Sortby:_params.searchInfo.Sortby,Isvip:_params.searchInfo.Isvip,selectSize:pageSize},type:'get',dataType:"json",success:function(data){if(data.ListHTMl){$("#noveslHtml").html(data.ListHTMl);if(!_pager){_pager=$("#pageHtml1").pagination(data.PageCount,{'callback':_getBookList,'showPageInput':true});$("#pageHtml2").pagination(data.PageCount,{'callback':_getBookList,'showPageInput':true});}
if(!isLoadPage){window.location.hash="";window.location.hash="allBookList";}}else if(data.noresultHTMl){$("#noveslHtml").html(data.noresultHTMl);}}});}
function _switchShowTab(){if(_showType===1){$("#bookListBox").hide();$("#detailedBookListPanel").show();}else{$("#bookListBox").show();$("#detailedBookListPanel").hide();}
$("#detailedlyShow").click(function(){_showType=1;$("#bookListBox").hide();$("#detailedBookListPanel").show();});$("#simplyShow").click(function(){_showType=2;$("#bookListBox").show();$("#detailedBookListPanel").hide();});}
_util.initNameSpace("CS.page.search");CS.page.search.allbooks={"init":init};})(jQuery);