<?php
$jieqiConfigs['system'] = array (
  'onlinetime' => 1800,
  'maxmessages' => 50,
  'maxdaymsg' => 0,
  'maxfriends' => 50,
  'checkcodelogin' => '0',
  'usegd' => '0',
  'regtimelimit' => 0,
  'usernamelimit' => '0',
  'avatardir' => 'C:/xiaoshuo/files/system/avatar',
  'avatarurl' => 'http://www.888yanqing.com/files/system/avatar',
  'avatartype' => '.gif .jpg .jpeg .png',
  'avatarcut' => '1',
  'avatarsize' => 1000,
  'fakeuserinfo' => '',
  'fakeuserpage' => '',
  'fakeuserlogin' => '',
  'fakeuserregister' => '',
  'fakeuserlogout' => '',
  'fakeuseruseredit' => '',
  'fakeusersetavatar' => '',
  'fakeuserpassedit' => '',
  'mailtype' => '0',
  'maildelimiter' => '1',
  'mailserver' => '',
  'mailport' => 25,
  'mailauth' => '1',
  'mailfrom' => '',
  'mailuser' => '',
  'mailpassword' => '',
  'posttitlemax' => 60,
  'postintervaltime' => 0,
  'postdenytimes' => '',
  'postdenywords' => '',
  'postreplacewords' => '',
  'postminsize' => 0,
  'postmaxsize' => 0,
  'postdenyrubbish' => '0',
  'postcheckcode' => '0',
);

?>