<?php
$jieqiBlocks['1'] = array (
  'bid' => 0,
  'blockname' => '新闻',
  'module' => 'news',
  'filename' => 'block_newslist',
  'classname' => 'BlockNewsList',
  'side' => -1,
  'title' => '',
  'vars' => 'firstid,0,4,0',
  'template' => 'block_newslist.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

$jieqiBlocks['2'] = array (
  'bid' => 0,
  'blockname' => '本周强推',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'toptime,10,0,0,0,0,0',
  'template' => 'index_tuijian.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);
$jieqiBlocks['3'] = array (
  'bid' => 0,
  'blockname' => '新闻',
  'module' => 'news',
  'filename' => 'block_newslist',
  'classname' => 'BlockNewsList',
  'side' => -1,
  'title' => '',
  'vars' => '0,0,4,0',
  'template' => 'block_newslist.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);
$jieqiBlocks['4'] = array (
  'bid' => 0,
  'blockname' => '封面推荐',
  'module' => 'article',
  'filename' => 'block_commend',
  'classname' => 'BlockArticleCommend',
  'side' => -1,
  'title' => '',
  'vars' => '1|2|3|4|5',
  'template' => 'index_fengmian.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);


$jieqiBlocks['5'] = array (
  'bid' => 0,
  'blockname' => '本站热推',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'postdate,10,0,0,0,0,0',
  'template' => 'index_tuijian.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

$jieqiBlocks['6'] = array (
  'bid' => 0,
  'blockname' => '现言·青春',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'allvote,5,2|5,0,0,0,0',
  'template' => 'index_fenlei.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

$jieqiBlocks['7'] = array (
  'bid' => 0,
  'blockname' => '古言·穿越',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'allvote,5,1|3,0,0,0,0',
  'template' => 'index_fenlei.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

$jieqiBlocks['8'] = array (
  'bid' => 0,
  'blockname' => '幻情·灵异',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'allvote,5,4|7,0,0,0,0',
  'template' => 'index_fenlei.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

$jieqiBlocks['9'] = array (
  'bid' => 0,
  'blockname' => '纯爱·同人',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'allvote,5,6|8,0,0,0,0',
  'template' => 'index_fenlei.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

$jieqiBlocks['10'] = array (
  'bid' => 0,
  'blockname' => '鲜花榜',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'allflower,10,0,0,0,0,0',
  'template' => 'index_fengyun.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

$jieqiBlocks['11'] = array (
  'bid' => 0,
  'blockname' => '月票榜',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'allvipvote,10,0,0,0,0,0',
  'template' => 'index_fengyun.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);


$jieqiBlocks['13'] = array (
  'bid' => 0,
  'blockname' => '总推荐榜',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'allvote,11,0,0,0,0,0',
  'template' => 'index_fengyun.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

$jieqiBlocks['14'] = array (
  'bid' => 0,
  'blockname' => '月票榜',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'allvipvote,11,0,0,0,0,0',
  'template' => 'index_fengyun.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);


$jieqiBlocks['16'] = array (
  'bid' => 0,
  'blockname' => '古代·言情 ',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'allvote,15,8,0,0,0,0',
  'template' => 'index_fenlei.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

$jieqiBlocks['17'] = array (
  'bid' => 0,
  'blockname' => '推荐榜',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'allvote,10,0,0,0,0,0',
  'template' => 'index_fengyun.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

$jieqiBlocks['18'] = array (
  'bid' => 0,
  'blockname' => '字数榜',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'size,11,0,0,0,0,0',
  'template' => 'index_fengyun.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

$jieqiBlocks['21'] = array (
  'bid' => 0,
  'blockname' => '最近更新',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'lastupdate,20,0,0,0,0,0',
  'template' => 'index_gengxin.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);


$jieqiBlocks['25'] = array (
  'bid' => 0,
  'blockname' => '最新入库榜',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'postdate,10,0,0,0,0,0',
  'template' => 'index_ruku.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

$jieqiBlocks['26'] = array (
  'bid' => 0,
  'blockname' => '友情链接',
  'module' => 'link',
  'filename' => 'block_linklist',
  'classname' => 'BlockLinkLinklist',
  'side' => -1,
  'title' => '',
  'vars' => '10,0,0,64',
  'template' => 'block_linklist.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);
?>