<?php 
$jieqiBlocks['1'] = array (
  'bid' => 0,
  'blockname' => '我的书架',
  'module' => 'article',
  'filename' => 'block_ubookcase',
  'classname' => 'BlockArticleUbookcase',
  'side' => -1,
  'title' => '',
  'vars' => 'lastupdate,5,0,$uid,0',
  'template' => 'block_ubookcase.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);
$jieqiBlocks['2'] = array (
  'bid' => 0,
  'blockname' => '我的工具箱',
  'module' => 'system',
  'filename' => 'block_userbox',
  'classname' => 'BlockSystemUserbox',
  'side' => -1,
  'title' => '',
  'vars' => '',
  'template' => 'block_tool.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);
$jieqiBlocks['3'] = array (
  'bid' => 0,
  'blockname' => '我的资料',
  'module' => 'system',
  'filename' => 'block_userstatus',
  'classname' => 'BlockSystemUserstatus',
  'side' => -1,
  'title' => '',
  'vars' => '',
  'template' => 'block_usersg.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);
?>